name: main
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  files:
    name: Changed Files
    runs-on: [ubuntu-latest]
    permissions:
      pull-requests: read
    outputs:
      keys: ${{ steps.files.outputs.changed_keys }}
      md_all_changed_files: ${{ steps.files.outputs.md_all_changed_files }}
      yml_all_changed_files: ${{ steps.files.outputs.yml_all_changed_files }}
      all_changed_files: ${{ steps.files.outputs.all_changed_files }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Get changed files by types
        uses: tj-actions/changed-files@v44
        id: files
        with:
          separator: ","
          files_yaml: |
            md:
              - '**.md'
            yml:
              - '**.yml'
      - run: |
          echo changed_keys ${{ steps.files.outputs.changed_keys }}

          echo md_any_changed ${{ steps.files.outputs.md_any_changed }}
          echo md_all_changed_files ${{ steps.files.outputs.md_all_changed_files }}

          echo yml_any_changed ${{ steps.files.outputs.yml_any_changed }}
          echo yml_all_changed_files ${{ steps.files.outputs.yml_all_changed_files }}

          echo changed_files ${{ steps.files.outputs.changed_files }}

          echo -e "DUMP: \n${{ toJSON(steps.files.outputs) }}"

  md:
    if: ${{ contains(needs.files.outputs.keys, 'md') }}
    name: List Files
    runs-on: [ubuntu-latest]
    needs: files
    env:
      WHOLE: ${{ needs.files.outputs.md_all_changed_files }}
    steps:
      - run: echo $WHOLE
      - run: echo ${{ needs.files.outputs.md_all_changed_files }}
      - name: Print all files
        env:
          SEPARATOR: ","
          CHANGED_FILES: ${{ needs.files.outputs.md_all_changed_files }}
        run: ${{ github.workspace }}/.github/actions/scripts/list_files.sh
