name: main
on:
  push:
    branches:
      - main

defaults:
  run:
    shell: /usr/bin/env -S bash -O globstar -xeo pipefail {0}

jobs:
  encache:
    runs-on: [ubuntu-latest]
    steps:
      - run: |
          mkdir -vp test
          echo "${{runner.os}}" > test/expression-test-1-key-${{ runner.os }}
      - uses: actions/cache@v4
        with:
          path: |
            test
          key: expression-test-1-key-${{ runner.os }}
          restore-keys: |
            expression-test-1-key

  decache:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/cache@4
        with:
          path: |
            test
          key: expression-test-1-key-${{ runner.os }}
          restore-keys: |
            expression-test-1-key
      - run: cat test/expression-test-1-key-${{ runner.os }}
