name: main
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

defaults:
  run:
    shell: bash -xeo pipefail {0}

jobs:
  files:
    name: Changed Files
    runs-on: [ubuntu-latest]
    permissions:
      pull-requests: read
    outputs:
      keys: ${{ steps.files.outputs.changed_keys }}
      changed_files: ${{ toJSON(steps.files.outputs) }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Get changed files by types
        uses: tj-actions/changed-files@v44
        id: files
        with:
          separator: ","
          files_yaml: |
            md:
              - '**.md'
            yml:
              - '**.yml'
      - run: |
          echo changed_keys ${{ steps.files.outputs.changed_keys }}

          echo md_any_changed ${{ steps.files.outputs.md_any_changed }}
          echo md_all_changed_files ${{ steps.files.outputs.md_all_changed_files }}

          echo yml_any_changed ${{ steps.files.outputs.yml_any_changed }}
          echo yml_all_changed_files ${{ steps.files.outputs.yml_all_changed_files }}

          echo changed_files ${{ steps.files.outputs.changed_files }}

          echo -e "DUMP: \n${{ toJSON(steps.files.outputs) }}"

  md:
    if: ${{ contains(needs.files.outputs.keys, 'md') }}
    name: List Files
    runs-on: [ubuntu-latest]
    needs: files
    env:
      CHANGED_FILES: ${{ fromJSON(needs.files.outputs.changed_files)['md_all_changed_files'] }}
    steps:
      - run: ${{ fromJSON(needs.files.outputs.changed_files) }}
      - run: echo ${CHANGED_FILES}
      - run: pwd
      - run: ls .github/actions/scripts/list_files.sh
      - name: Print all files
        env:
          SEPARATOR: ","
          CHANGED_FILES: ${CHANGED_FILES}
        run: ./.github/actions/scripts/list_files.sh
