name: main
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  files:
    name: Changed Files
    runs-on: [ubuntu-latest]
    outputs:
      keys: ${{ steps.files.outputs.changed_keys }}
      md_any_changed: ${{ steps.files.outputs.md_any_changed }}
      md_all_changed_files: ${{ steps.files.outputs.md_all_changed_files }}
      all_changed_files: ${{ steps.files.outputs.all_changed_files }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Get changed files by types
        uses: tj-actions/changed-files@v44
        id: files
        with:
          separator: ","
          files_yaml: |
            md:
              - '**.md'
            yml:
              - '**.yml'
      - run: |
          echo changed_keys ${{ steps.files.outputs.changed_keys }}
          echo md_any_changed ${{ steps.files.outputs.md_any_changed }}
          echo md_all_changed_files ${{ steps.files.outputs.md_all_changed_files }}
          echo all_changed_files ${{ steps.files.outputs.all_changed_files }}

  list:
    if: ${{ contains(needs.files.outputs.changed, 'md') }}
    name: List Files
    runs-on: [ubuntu-latest]
    needs: files
    env:
      WHOLE: ${{ needs.files.outputs.md_all_changed_files }}
    steps:
      - run: echo $WHOLE
      - name: Print all files
        env:
          SEPARATOR: ","
          CHANGED_FILES: ${{ steps.files.outputs.whole.md_changed_files }}
        run: .github/actions/scripts/list_files.sh
