name: main
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

defaults:
  run:
    shell: bash -xeo pipefail {0}

jobs:
  files:
    name: Changed Files
    runs-on: [ubuntu-latest]
    permissions:
      pull-requests: read
    outputs:
      keys: ${{ steps.files.outputs.changed_keys }}
      changed_files: ${{ toJSON(steps.files.outputs) }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Get changed files by types
        uses: tj-actions/changed-files@v44
        id: files
        with:
          separator: ","
          files_yaml: |
            md:
              - '**.md'
            yml:
              - '**.yml'
      - run: |
          echo changed_keys ${{ steps.files.outputs.changed_keys }}
          echo ${{ toJSON(steps.files.outputs) }}

  md:
    if: ${{ contains(needs.files.outputs.keys, 'md') }}
    name: List md Files
    runs-on: [ubuntu-latest]
    needs: files
    env:
      CHANGED_FILES: ${{ fromJSON(needs.files.outputs.changed_files)['md_all_changed_files'] }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Print all files
        env:
          SEPARATOR: ","
        run: .github/actions/scripts/list_files.sh

  yml:
    if: ${{ contains(needs.files.outputs.keys, 'yml') }}
    name: List yml Files
    runs-on: [ubuntu-latest]
    needs: files
    env:
      CHANGED_FILES: ${{ fromJSON(needs.files.outputs.changed_files)['yml_all_changed_files'] }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Print all files
        env:
          SEPARATOR: ","
        run: .github/actions/scripts/list_files.sh
